//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.CompilerServices;

namespace ParixClient.emiliaromagna.servizicner
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://parixgate.infocamere.it/services/gate", ConfigurationName="ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl")]
    public interface ICRSimpleWSImpl
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerCodiceFiscaleResponse> RicercaImpreseNonCessatePerCodiceFiscaleAsync(ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerCodiceFiscaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpresePerCodiceFiscaleResponse> RicercaImpresePerCodiceFiscaleAsync(ParixClient.emiliaromagna.servizicner.RicercaImpresePerCodiceFiscaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerDenominazioneResponse> RicercaImpreseNonCessatePerDenominazioneAsync(ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerDenominazioneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpresePerDenominazioneResponse> RicercaImpresePerDenominazioneAsync(ParixClient.emiliaromagna.servizicner.RicercaImpresePerDenominazioneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaPersoneNonCessatePerCodiceFiscaleResponse> RicercaPersoneNonCessatePerCodiceFiscaleAsync(ParixClient.emiliaromagna.servizicner.RicercaPersoneNonCessatePerCodiceFiscaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaPersonePerCodiceFiscaleResponse> RicercaPersonePerCodiceFiscaleAsync(ParixClient.emiliaromagna.servizicner.RicercaPersonePerCodiceFiscaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpresePerPeriodoVariazioneResponse> RicercaImpresePerPeriodoVariazioneAsync(ParixClient.emiliaromagna.servizicner.RicercaImpresePerPeriodoVariazioneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioCompletoImpresaResponse> DettaglioCompletoImpresaAsync(ParixClient.emiliaromagna.servizicner.DettaglioCompletoImpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioRidottoImpresaResponse> DettaglioRidottoImpresaAsync(ParixClient.emiliaromagna.servizicner.DettaglioRidottoImpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaliImpresaResponse> DettaglioUnitaLocaliImpresaAsync(ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaliImpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaleImpresaResponse> DettaglioUnitaLocaleImpresaAsync(ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaleImpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioPersoneConCaricaResponse> DettaglioPersoneConCaricaAsync(ParixClient.emiliaromagna.servizicner.DettaglioPersoneConCaricaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioPersonaConCaricaResponse> DettaglioPersonaConCaricaAsync(ParixClient.emiliaromagna.servizicner.DettaglioPersonaConCaricaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaImpreseNonCessatePerCodiceFiscale", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class RicercaImpreseNonCessatePerCodiceFiscaleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string codice_fiscale;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string switch_control;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string password;
        
        public RicercaImpreseNonCessatePerCodiceFiscaleRequest()
        {
        }
        
        public RicercaImpreseNonCessatePerCodiceFiscaleRequest(string codice_fiscale, string switch_control, string user, string password)
        {
            this.codice_fiscale = codice_fiscale;
            this.switch_control = switch_control;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaImpreseNonCessatePerCodiceFiscaleResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class RicercaImpreseNonCessatePerCodiceFiscaleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RicercaImpreseNonCessatePerCodiceFiscaleReturn;
        
        public RicercaImpreseNonCessatePerCodiceFiscaleResponse()
        {
        }
        
        public RicercaImpreseNonCessatePerCodiceFiscaleResponse(string RicercaImpreseNonCessatePerCodiceFiscaleReturn)
        {
            this.RicercaImpreseNonCessatePerCodiceFiscaleReturn = RicercaImpreseNonCessatePerCodiceFiscaleReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaImpresePerCodiceFiscale", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class RicercaImpresePerCodiceFiscaleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string codice_fiscale;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string switch_control;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string password;
        
        public RicercaImpresePerCodiceFiscaleRequest()
        {
        }
        
        public RicercaImpresePerCodiceFiscaleRequest(string codice_fiscale, string switch_control, string user, string password)
        {
            this.codice_fiscale = codice_fiscale;
            this.switch_control = switch_control;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaImpresePerCodiceFiscaleResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class RicercaImpresePerCodiceFiscaleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RicercaImpresePerCodiceFiscaleReturn;
        
        public RicercaImpresePerCodiceFiscaleResponse()
        {
        }
        
        public RicercaImpresePerCodiceFiscaleResponse(string RicercaImpresePerCodiceFiscaleReturn)
        {
            this.RicercaImpresePerCodiceFiscaleReturn = RicercaImpresePerCodiceFiscaleReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaImpreseNonCessatePerDenominazione", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class RicercaImpreseNonCessatePerDenominazioneRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string denominazione_sede;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string switch_control;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string password;
        
        public RicercaImpreseNonCessatePerDenominazioneRequest()
        {
        }
        
        public RicercaImpreseNonCessatePerDenominazioneRequest(string denominazione_sede, string switch_control, string user, string password)
        {
            this.denominazione_sede = denominazione_sede;
            this.switch_control = switch_control;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaImpreseNonCessatePerDenominazioneResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class RicercaImpreseNonCessatePerDenominazioneResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RicercaImpreseNonCessatePerDenominazioneReturn;
        
        public RicercaImpreseNonCessatePerDenominazioneResponse()
        {
        }
        
        public RicercaImpreseNonCessatePerDenominazioneResponse(string RicercaImpreseNonCessatePerDenominazioneReturn)
        {
            this.RicercaImpreseNonCessatePerDenominazioneReturn = RicercaImpreseNonCessatePerDenominazioneReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaImpresePerDenominazione", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class RicercaImpresePerDenominazioneRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string denominazione_sede;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string switch_control;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string password;
        
        public RicercaImpresePerDenominazioneRequest()
        {
        }
        
        public RicercaImpresePerDenominazioneRequest(string denominazione_sede, string switch_control, string user, string password)
        {
            this.denominazione_sede = denominazione_sede;
            this.switch_control = switch_control;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaImpresePerDenominazioneResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class RicercaImpresePerDenominazioneResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RicercaImpresePerDenominazioneReturn;
        
        public RicercaImpresePerDenominazioneResponse()
        {
        }
        
        public RicercaImpresePerDenominazioneResponse(string RicercaImpresePerDenominazioneReturn)
        {
            this.RicercaImpresePerDenominazioneReturn = RicercaImpresePerDenominazioneReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaPersoneNonCessatePerCodiceFiscale", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class RicercaPersoneNonCessatePerCodiceFiscaleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string codice_fiscale;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string codice_carica;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string password;
        
        public RicercaPersoneNonCessatePerCodiceFiscaleRequest()
        {
        }
        
        public RicercaPersoneNonCessatePerCodiceFiscaleRequest(string codice_fiscale, string codice_carica, string user, string password)
        {
            this.codice_fiscale = codice_fiscale;
            this.codice_carica = codice_carica;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaPersoneNonCessatePerCodiceFiscaleResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class RicercaPersoneNonCessatePerCodiceFiscaleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RicercaPersoneNonCessatePerCodiceFiscaleReturn;
        
        public RicercaPersoneNonCessatePerCodiceFiscaleResponse()
        {
        }
        
        public RicercaPersoneNonCessatePerCodiceFiscaleResponse(string RicercaPersoneNonCessatePerCodiceFiscaleReturn)
        {
            this.RicercaPersoneNonCessatePerCodiceFiscaleReturn = RicercaPersoneNonCessatePerCodiceFiscaleReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaPersonePerCodiceFiscale", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class RicercaPersonePerCodiceFiscaleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string codice_fiscale;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string codice_carica;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string password;
        
        public RicercaPersonePerCodiceFiscaleRequest()
        {
        }
        
        public RicercaPersonePerCodiceFiscaleRequest(string codice_fiscale, string codice_carica, string user, string password)
        {
            this.codice_fiscale = codice_fiscale;
            this.codice_carica = codice_carica;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaPersonePerCodiceFiscaleResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class RicercaPersonePerCodiceFiscaleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RicercaPersonePerCodiceFiscaleReturn;
        
        public RicercaPersonePerCodiceFiscaleResponse()
        {
        }
        
        public RicercaPersonePerCodiceFiscaleResponse(string RicercaPersonePerCodiceFiscaleReturn)
        {
            this.RicercaPersonePerCodiceFiscaleReturn = RicercaPersonePerCodiceFiscaleReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaImpresePerPeriodoVariazione", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class RicercaImpresePerPeriodoVariazioneRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string dt_ult_agg_ri_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string dt_ult_agg_ri_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cciaa_regz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string password;
        
        public RicercaImpresePerPeriodoVariazioneRequest()
        {
        }
        
        public RicercaImpresePerPeriodoVariazioneRequest(string dt_ult_agg_ri_1, string dt_ult_agg_ri_2, string cciaa_regz, string user, string password)
        {
            this.dt_ult_agg_ri_1 = dt_ult_agg_ri_1;
            this.dt_ult_agg_ri_2 = dt_ult_agg_ri_2;
            this.cciaa_regz = cciaa_regz;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RicercaImpresePerPeriodoVariazioneResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class RicercaImpresePerPeriodoVariazioneResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RicercaImpresePerPeriodoVariazioneReturn;
        
        public RicercaImpresePerPeriodoVariazioneResponse()
        {
        }
        
        public RicercaImpresePerPeriodoVariazioneResponse(string RicercaImpresePerPeriodoVariazioneReturn)
        {
            this.RicercaImpresePerPeriodoVariazioneReturn = RicercaImpresePerPeriodoVariazioneReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DettaglioCompletoImpresa", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class DettaglioCompletoImpresaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sgl_prv_sede;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string n_rea_sede;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string switch_control;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string abilitaSoci;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string password;
        
        public DettaglioCompletoImpresaRequest()
        {
        }
        
        public DettaglioCompletoImpresaRequest(string sgl_prv_sede, string n_rea_sede, string switch_control, string abilitaSoci, string user, string password)
        {
            this.sgl_prv_sede = sgl_prv_sede;
            this.n_rea_sede = n_rea_sede;
            this.switch_control = switch_control;
            this.abilitaSoci = abilitaSoci;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DettaglioCompletoImpresaResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class DettaglioCompletoImpresaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string DettaglioCompletoImpresaReturn;
        
        public DettaglioCompletoImpresaResponse()
        {
        }
        
        public DettaglioCompletoImpresaResponse(string DettaglioCompletoImpresaReturn)
        {
            this.DettaglioCompletoImpresaReturn = DettaglioCompletoImpresaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DettaglioRidottoImpresa", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class DettaglioRidottoImpresaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sgl_prv_sede;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string n_rea_sede;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string switch_control;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string password;
        
        public DettaglioRidottoImpresaRequest()
        {
        }
        
        public DettaglioRidottoImpresaRequest(string sgl_prv_sede, string n_rea_sede, string switch_control, string user, string password)
        {
            this.sgl_prv_sede = sgl_prv_sede;
            this.n_rea_sede = n_rea_sede;
            this.switch_control = switch_control;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DettaglioRidottoImpresaResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class DettaglioRidottoImpresaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string DettaglioRidottoImpresaReturn;
        
        public DettaglioRidottoImpresaResponse()
        {
        }
        
        public DettaglioRidottoImpresaResponse(string DettaglioRidottoImpresaReturn)
        {
            this.DettaglioRidottoImpresaReturn = DettaglioRidottoImpresaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DettaglioUnitaLocaliImpresa", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class DettaglioUnitaLocaliImpresaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string fk_rea_cciaa_regz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string fk_rea_n_rea;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string switch_control;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string password;
        
        public DettaglioUnitaLocaliImpresaRequest()
        {
        }
        
        public DettaglioUnitaLocaliImpresaRequest(string fk_rea_cciaa_regz, string fk_rea_n_rea, string switch_control, string user, string password)
        {
            this.fk_rea_cciaa_regz = fk_rea_cciaa_regz;
            this.fk_rea_n_rea = fk_rea_n_rea;
            this.switch_control = switch_control;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DettaglioUnitaLocaliImpresaResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class DettaglioUnitaLocaliImpresaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string DettaglioUnitaLocaliImpresaReturn;
        
        public DettaglioUnitaLocaliImpresaResponse()
        {
        }
        
        public DettaglioUnitaLocaliImpresaResponse(string DettaglioUnitaLocaliImpresaReturn)
        {
            this.DettaglioUnitaLocaliImpresaReturn = DettaglioUnitaLocaliImpresaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DettaglioUnitaLocaleImpresa", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class DettaglioUnitaLocaleImpresaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string fk_rea_cciaa_regz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string fk_rea_n_rea;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string pro_localizzazione;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string switch_control;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string password;
        
        public DettaglioUnitaLocaleImpresaRequest()
        {
        }
        
        public DettaglioUnitaLocaleImpresaRequest(string fk_rea_cciaa_regz, string fk_rea_n_rea, string pro_localizzazione, string switch_control, string user, string password)
        {
            this.fk_rea_cciaa_regz = fk_rea_cciaa_regz;
            this.fk_rea_n_rea = fk_rea_n_rea;
            this.pro_localizzazione = pro_localizzazione;
            this.switch_control = switch_control;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DettaglioUnitaLocaleImpresaResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class DettaglioUnitaLocaleImpresaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string DettaglioUnitaLocaleImpresaReturn;
        
        public DettaglioUnitaLocaleImpresaResponse()
        {
        }
        
        public DettaglioUnitaLocaleImpresaResponse(string DettaglioUnitaLocaleImpresaReturn)
        {
            this.DettaglioUnitaLocaleImpresaReturn = DettaglioUnitaLocaleImpresaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DettaglioPersoneConCarica", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class DettaglioPersoneConCaricaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string fk_pri_cciaa_regz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string fk_pri_n_rea;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string switch_control;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string password;
        
        public DettaglioPersoneConCaricaRequest()
        {
        }
        
        public DettaglioPersoneConCaricaRequest(string fk_pri_cciaa_regz, string fk_pri_n_rea, string switch_control, string user, string password)
        {
            this.fk_pri_cciaa_regz = fk_pri_cciaa_regz;
            this.fk_pri_n_rea = fk_pri_n_rea;
            this.switch_control = switch_control;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DettaglioPersoneConCaricaResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class DettaglioPersoneConCaricaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string DettaglioPersoneConCaricaReturn;
        
        public DettaglioPersoneConCaricaResponse()
        {
        }
        
        public DettaglioPersoneConCaricaResponse(string DettaglioPersoneConCaricaReturn)
        {
            this.DettaglioPersoneConCaricaReturn = DettaglioPersoneConCaricaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DettaglioPersonaConCarica", WrapperNamespace="http://ws.icr.ic.it", IsWrapped=true)]
    public partial class DettaglioPersonaConCaricaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string fk_pri_cciaa_regz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string fk_pri_n_rea;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string pro_persona;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string switch_control;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string password;
        
        public DettaglioPersonaConCaricaRequest()
        {
        }
        
        public DettaglioPersonaConCaricaRequest(string fk_pri_cciaa_regz, string fk_pri_n_rea, string pro_persona, string switch_control, string user, string password)
        {
            this.fk_pri_cciaa_regz = fk_pri_cciaa_regz;
            this.fk_pri_n_rea = fk_pri_n_rea;
            this.pro_persona = pro_persona;
            this.switch_control = switch_control;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DettaglioPersonaConCaricaResponse", WrapperNamespace="http://parixgate.infocamere.it/services/gate", IsWrapped=true)]
    public partial class DettaglioPersonaConCaricaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string DettaglioPersonaConCaricaReturn;
        
        public DettaglioPersonaConCaricaResponse()
        {
        }
        
        public DettaglioPersonaConCaricaResponse(string DettaglioPersonaConCaricaReturn)
        {
            this.DettaglioPersonaConCaricaReturn = DettaglioPersonaConCaricaReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ICRSimpleWSImplChannel : ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CRSimpleWSImplClient : System.ServiceModel.ClientBase<ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl>, ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CRSimpleWSImplClient() : 
                base(CRSimpleWSImplClient.GetDefaultBinding(), CRSimpleWSImplClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.gate.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CRSimpleWSImplClient(EndpointConfiguration endpointConfiguration) : 
                base(CRSimpleWSImplClient.GetBindingForEndpoint(endpointConfiguration), CRSimpleWSImplClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CRSimpleWSImplClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CRSimpleWSImplClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CRSimpleWSImplClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CRSimpleWSImplClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CRSimpleWSImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerCodiceFiscaleResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.RicercaImpreseNonCessatePerCodiceFiscaleAsync(ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerCodiceFiscaleRequest request)
        {
            return base.Channel.RicercaImpreseNonCessatePerCodiceFiscaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerCodiceFiscaleResponse> RicercaImpreseNonCessatePerCodiceFiscaleAsync(string codice_fiscale, string switch_control, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerCodiceFiscaleRequest inValue = new ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerCodiceFiscaleRequest();
            inValue.codice_fiscale = codice_fiscale;
            inValue.switch_control = switch_control;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).RicercaImpreseNonCessatePerCodiceFiscaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpresePerCodiceFiscaleResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.RicercaImpresePerCodiceFiscaleAsync(ParixClient.emiliaromagna.servizicner.RicercaImpresePerCodiceFiscaleRequest request)
        {
            return base.Channel.RicercaImpresePerCodiceFiscaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpresePerCodiceFiscaleResponse> RicercaImpresePerCodiceFiscaleAsync(string codice_fiscale, string switch_control, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.RicercaImpresePerCodiceFiscaleRequest inValue = new ParixClient.emiliaromagna.servizicner.RicercaImpresePerCodiceFiscaleRequest();
            inValue.codice_fiscale = codice_fiscale;
            inValue.switch_control = switch_control;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).RicercaImpresePerCodiceFiscaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerDenominazioneResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.RicercaImpreseNonCessatePerDenominazioneAsync(ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerDenominazioneRequest request)
        {
            return base.Channel.RicercaImpreseNonCessatePerDenominazioneAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerDenominazioneResponse> RicercaImpreseNonCessatePerDenominazioneAsync(string denominazione_sede, string switch_control, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerDenominazioneRequest inValue = new ParixClient.emiliaromagna.servizicner.RicercaImpreseNonCessatePerDenominazioneRequest();
            inValue.denominazione_sede = denominazione_sede;
            inValue.switch_control = switch_control;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).RicercaImpreseNonCessatePerDenominazioneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpresePerDenominazioneResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.RicercaImpresePerDenominazioneAsync(ParixClient.emiliaromagna.servizicner.RicercaImpresePerDenominazioneRequest request)
        {
            return base.Channel.RicercaImpresePerDenominazioneAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpresePerDenominazioneResponse> RicercaImpresePerDenominazioneAsync(string denominazione_sede, string switch_control, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.RicercaImpresePerDenominazioneRequest inValue = new ParixClient.emiliaromagna.servizicner.RicercaImpresePerDenominazioneRequest();
            inValue.denominazione_sede = denominazione_sede;
            inValue.switch_control = switch_control;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).RicercaImpresePerDenominazioneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaPersoneNonCessatePerCodiceFiscaleResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.RicercaPersoneNonCessatePerCodiceFiscaleAsync(ParixClient.emiliaromagna.servizicner.RicercaPersoneNonCessatePerCodiceFiscaleRequest request)
        {
            return base.Channel.RicercaPersoneNonCessatePerCodiceFiscaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaPersoneNonCessatePerCodiceFiscaleResponse> RicercaPersoneNonCessatePerCodiceFiscaleAsync(string codice_fiscale, string codice_carica, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.RicercaPersoneNonCessatePerCodiceFiscaleRequest inValue = new ParixClient.emiliaromagna.servizicner.RicercaPersoneNonCessatePerCodiceFiscaleRequest();
            inValue.codice_fiscale = codice_fiscale;
            inValue.codice_carica = codice_carica;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).RicercaPersoneNonCessatePerCodiceFiscaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaPersonePerCodiceFiscaleResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.RicercaPersonePerCodiceFiscaleAsync(ParixClient.emiliaromagna.servizicner.RicercaPersonePerCodiceFiscaleRequest request)
        {
            return base.Channel.RicercaPersonePerCodiceFiscaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaPersonePerCodiceFiscaleResponse> RicercaPersonePerCodiceFiscaleAsync(string codice_fiscale, string codice_carica, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.RicercaPersonePerCodiceFiscaleRequest inValue = new ParixClient.emiliaromagna.servizicner.RicercaPersonePerCodiceFiscaleRequest();
            inValue.codice_fiscale = codice_fiscale;
            inValue.codice_carica = codice_carica;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).RicercaPersonePerCodiceFiscaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpresePerPeriodoVariazioneResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.RicercaImpresePerPeriodoVariazioneAsync(ParixClient.emiliaromagna.servizicner.RicercaImpresePerPeriodoVariazioneRequest request)
        {
            return base.Channel.RicercaImpresePerPeriodoVariazioneAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.RicercaImpresePerPeriodoVariazioneResponse> RicercaImpresePerPeriodoVariazioneAsync(string dt_ult_agg_ri_1, string dt_ult_agg_ri_2, string cciaa_regz, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.RicercaImpresePerPeriodoVariazioneRequest inValue = new ParixClient.emiliaromagna.servizicner.RicercaImpresePerPeriodoVariazioneRequest();
            inValue.dt_ult_agg_ri_1 = dt_ult_agg_ri_1;
            inValue.dt_ult_agg_ri_2 = dt_ult_agg_ri_2;
            inValue.cciaa_regz = cciaa_regz;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).RicercaImpresePerPeriodoVariazioneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioCompletoImpresaResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.DettaglioCompletoImpresaAsync(ParixClient.emiliaromagna.servizicner.DettaglioCompletoImpresaRequest request)
        {
            return base.Channel.DettaglioCompletoImpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioCompletoImpresaResponse> DettaglioCompletoImpresaAsync(string sgl_prv_sede, string n_rea_sede, string switch_control, string abilitaSoci, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.DettaglioCompletoImpresaRequest inValue = new ParixClient.emiliaromagna.servizicner.DettaglioCompletoImpresaRequest();
            inValue.sgl_prv_sede = sgl_prv_sede;
            inValue.n_rea_sede = n_rea_sede;
            inValue.switch_control = switch_control;
            inValue.abilitaSoci = abilitaSoci;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).DettaglioCompletoImpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioRidottoImpresaResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.DettaglioRidottoImpresaAsync(ParixClient.emiliaromagna.servizicner.DettaglioRidottoImpresaRequest request)
        {
            return base.Channel.DettaglioRidottoImpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioRidottoImpresaResponse> DettaglioRidottoImpresaAsync(string sgl_prv_sede, string n_rea_sede, string switch_control, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.DettaglioRidottoImpresaRequest inValue = new ParixClient.emiliaromagna.servizicner.DettaglioRidottoImpresaRequest();
            inValue.sgl_prv_sede = sgl_prv_sede;
            inValue.n_rea_sede = n_rea_sede;
            inValue.switch_control = switch_control;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).DettaglioRidottoImpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaliImpresaResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.DettaglioUnitaLocaliImpresaAsync(ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaliImpresaRequest request)
        {
            return base.Channel.DettaglioUnitaLocaliImpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaliImpresaResponse> DettaglioUnitaLocaliImpresaAsync(string fk_rea_cciaa_regz, string fk_rea_n_rea, string switch_control, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaliImpresaRequest inValue = new ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaliImpresaRequest();
            inValue.fk_rea_cciaa_regz = fk_rea_cciaa_regz;
            inValue.fk_rea_n_rea = fk_rea_n_rea;
            inValue.switch_control = switch_control;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).DettaglioUnitaLocaliImpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaleImpresaResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.DettaglioUnitaLocaleImpresaAsync(ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaleImpresaRequest request)
        {
            return base.Channel.DettaglioUnitaLocaleImpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaleImpresaResponse> DettaglioUnitaLocaleImpresaAsync(string fk_rea_cciaa_regz, string fk_rea_n_rea, string pro_localizzazione, string switch_control, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaleImpresaRequest inValue = new ParixClient.emiliaromagna.servizicner.DettaglioUnitaLocaleImpresaRequest();
            inValue.fk_rea_cciaa_regz = fk_rea_cciaa_regz;
            inValue.fk_rea_n_rea = fk_rea_n_rea;
            inValue.pro_localizzazione = pro_localizzazione;
            inValue.switch_control = switch_control;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).DettaglioUnitaLocaleImpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioPersoneConCaricaResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.DettaglioPersoneConCaricaAsync(ParixClient.emiliaromagna.servizicner.DettaglioPersoneConCaricaRequest request)
        {
            return base.Channel.DettaglioPersoneConCaricaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioPersoneConCaricaResponse> DettaglioPersoneConCaricaAsync(string fk_pri_cciaa_regz, string fk_pri_n_rea, string switch_control, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.DettaglioPersoneConCaricaRequest inValue = new ParixClient.emiliaromagna.servizicner.DettaglioPersoneConCaricaRequest();
            inValue.fk_pri_cciaa_regz = fk_pri_cciaa_regz;
            inValue.fk_pri_n_rea = fk_pri_n_rea;
            inValue.switch_control = switch_control;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).DettaglioPersoneConCaricaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioPersonaConCaricaResponse> ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl.DettaglioPersonaConCaricaAsync(ParixClient.emiliaromagna.servizicner.DettaglioPersonaConCaricaRequest request)
        {
            return base.Channel.DettaglioPersonaConCaricaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParixClient.emiliaromagna.servizicner.DettaglioPersonaConCaricaResponse> DettaglioPersonaConCaricaAsync(string fk_pri_cciaa_regz, string fk_pri_n_rea, string pro_persona, string switch_control, string user, string password)
        {
            ParixClient.emiliaromagna.servizicner.DettaglioPersonaConCaricaRequest inValue = new ParixClient.emiliaromagna.servizicner.DettaglioPersonaConCaricaRequest();
            inValue.fk_pri_cciaa_regz = fk_pri_cciaa_regz;
            inValue.fk_pri_n_rea = fk_pri_n_rea;
            inValue.pro_persona = pro_persona;
            inValue.switch_control = switch_control;
            inValue.user = user;
            inValue.password = password;
            return ((ParixClient.emiliaromagna.servizicner.ICRSimpleWSImpl)(this)).DettaglioPersonaConCaricaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.gate))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.gate))
            {
                return new System.ServiceModel.EndpointAddress("http://10.2.62.55:8080/parixgate/services/gate");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CRSimpleWSImplClient.GetBindingForEndpoint(EndpointConfiguration.gate);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CRSimpleWSImplClient.GetEndpointAddress(EndpointConfiguration.gate);
        }
        
        public enum EndpointConfiguration
        {
            
            gate,
        }

        
    }
}
