//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParixClient.it.lepida.adrier
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://adrigate.lepida.it", ConfigurationName="it.lepida.adrier.RicercaImprese")]
    public interface RicercaImprese
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DettaglioPersoneConCaricaReturn")]
        System.Threading.Tasks.Task<string> DettaglioPersoneConCaricaAsync(string fk_pri_cciaa_regz, string fk_pri_n_rea, string switch_control, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RicercaImpresePerCodiceFiscaleReturn")]
        System.Threading.Tasks.Task<string> RicercaImpresePerCodiceFiscaleAsync(string codice_fiscale, string switch_control, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RicercaImpresePerDenominazioneReturn")]
        System.Threading.Tasks.Task<string> RicercaImpresePerDenominazioneAsync(string denominazione_sede, string switch_control, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DettaglioImpresaNReaReturn")]
        System.Threading.Tasks.Task<string> DettaglioImpresaNReaAsync(string sgl_prv_sede, string n_rea_sede, string switch_control, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DettaglioRidottoImpresaReturn")]
        System.Threading.Tasks.Task<string> DettaglioRidottoImpresaAsync(string sgl_prv_sede, string n_rea_sede, string switch_control, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DettaglioCompletoImpresaReturn")]
        System.Threading.Tasks.Task<string> DettaglioCompletoImpresaAsync(string sgl_prv_sede, string n_rea_sede, string switch_control, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RicercaImpreseNReaReturn")]
        System.Threading.Tasks.Task<string> RicercaImpreseNReaAsync(string sgl_prv_sede, string n_rea_sede, string switch_control, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RicercaImpreseNonCessatePerCodiceFiscaleReturn")]
        System.Threading.Tasks.Task<string> RicercaImpreseNonCessatePerCodiceFiscaleAsync(string codice_fiscale, string switch_control, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RicercaImpreseNonCessatePerDenominazioneReturn")]
        System.Threading.Tasks.Task<string> RicercaImpreseNonCessatePerDenominazioneAsync(string denominazione_sede, string switch_control, string user, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface RicercaImpreseChannel : it.lepida.adrier.RicercaImprese, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class RicercaImpreseClient : System.ServiceModel.ClientBase<it.lepida.adrier.RicercaImprese>, it.lepida.adrier.RicercaImprese
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RicercaImpreseClient() : 
                base(RicercaImpreseClient.GetDefaultBinding(), RicercaImpreseClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RicercaImprese.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RicercaImpreseClient(EndpointConfiguration endpointConfiguration) : 
                base(RicercaImpreseClient.GetBindingForEndpoint(endpointConfiguration), RicercaImpreseClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RicercaImpreseClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RicercaImpreseClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RicercaImpreseClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RicercaImpreseClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RicercaImpreseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> DettaglioPersoneConCaricaAsync(string fk_pri_cciaa_regz, string fk_pri_n_rea, string switch_control, string user, string password)
        {
            return base.Channel.DettaglioPersoneConCaricaAsync(fk_pri_cciaa_regz, fk_pri_n_rea, switch_control, user, password);
        }
        
        public System.Threading.Tasks.Task<string> RicercaImpresePerCodiceFiscaleAsync(string codice_fiscale, string switch_control, string user, string password)
        {
            return base.Channel.RicercaImpresePerCodiceFiscaleAsync(codice_fiscale, switch_control, user, password);
        }
        
        public System.Threading.Tasks.Task<string> RicercaImpresePerDenominazioneAsync(string denominazione_sede, string switch_control, string user, string password)
        {
            return base.Channel.RicercaImpresePerDenominazioneAsync(denominazione_sede, switch_control, user, password);
        }
        
        public System.Threading.Tasks.Task<string> DettaglioImpresaNReaAsync(string sgl_prv_sede, string n_rea_sede, string switch_control, string user, string password)
        {
            return base.Channel.DettaglioImpresaNReaAsync(sgl_prv_sede, n_rea_sede, switch_control, user, password);
        }
        
        public System.Threading.Tasks.Task<string> DettaglioRidottoImpresaAsync(string sgl_prv_sede, string n_rea_sede, string switch_control, string user, string password)
        {
            return base.Channel.DettaglioRidottoImpresaAsync(sgl_prv_sede, n_rea_sede, switch_control, user, password);
        }
        
        public System.Threading.Tasks.Task<string> DettaglioCompletoImpresaAsync(string sgl_prv_sede, string n_rea_sede, string switch_control, string user, string password)
        {
            return base.Channel.DettaglioCompletoImpresaAsync(sgl_prv_sede, n_rea_sede, switch_control, user, password);
        }
        
        public System.Threading.Tasks.Task<string> RicercaImpreseNReaAsync(string sgl_prv_sede, string n_rea_sede, string switch_control, string user, string password)
        {
            return base.Channel.RicercaImpreseNReaAsync(sgl_prv_sede, n_rea_sede, switch_control, user, password);
        }
        
        public System.Threading.Tasks.Task<string> RicercaImpreseNonCessatePerCodiceFiscaleAsync(string codice_fiscale, string switch_control, string user, string password)
        {
            return base.Channel.RicercaImpreseNonCessatePerCodiceFiscaleAsync(codice_fiscale, switch_control, user, password);
        }
        
        public System.Threading.Tasks.Task<string> RicercaImpreseNonCessatePerDenominazioneAsync(string denominazione_sede, string switch_control, string user, string password)
        {
            return base.Channel.RicercaImpreseNonCessatePerDenominazioneAsync(denominazione_sede, switch_control, user, password);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RicercaImprese))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RicercaImprese))
            {
                return new System.ServiceModel.EndpointAddress("https://adrier.lepida.it/AdriGate/services/RicercaImprese");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RicercaImpreseClient.GetBindingForEndpoint(EndpointConfiguration.RicercaImprese);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RicercaImpreseClient.GetEndpointAddress(EndpointConfiguration.RicercaImprese);
        }
        
        public enum EndpointConfiguration
        {
            
            RicercaImprese,
        }
    }
}
